task:
  environment:
    CACHIX_SIGNING_KEY: ENCRYPTED[!cec502ed813cbcd0237697d2031f750186ff20eed5815b1ad950ad2f2d701702ae6ba2f0cb4cb1985687a696c8ee492c!]
    # Save some traffic by excluding the full git history
    CIRRUS_CLONE_DEPTH: 1

  # Use the maximum timeout. Needed when rebuilding packages on a channel update.
  timeout_in: 120m

  container:
    # Defined in https://github.com/nix-community/docker-nixpkgs
    # TODO-EXTERNAL:
    # Update to nixos-23.05 when https://github.com/nix-community/docker-nixpkgs/issues/57
    # has been resolved
    image: nixpkgs/nix-flakes:nixos-22.11

  matrix:
    - name: modules_test
      container:
        # Besides virtualization, this also enables privileged containers which are required for
        # sandboxed builds
        kvm: true
        # Needed for package builds
        memory: 8G
        # A maximum of 16 CPUs is shared among all concurrent tasks.
        # https://cirrus-ci.org/faq/#are-there-any-limits
        cpu: 4
      environment:
        matrix:
          - scenario: default
          - scenario: netns
          - scenario: netnsRegtest
          - scenario: trustedcoin
      # This script is run as root
      build_script:
        - echo "sandbox = true" >> /etc/nix/nix.conf
        # Use cachix 1.3.3 due to https://github.com/cachix/cachix/issues/529, which
        # breaks the CI build
        # TODO-EXTERNAL:
        # Switch to the default version when this issue has been resolved
        - nix shell --inputs-from . nixpkgs#{bash,coreutils} nixpkgs/eef86b8a942913a828b9ef13722835f359deef29#cachix -c ./test/ci/build.sh $scenario

    - name: flake
      build_script:
        - nix flake check
        - ./test/nixos-search/ci-test.sh

    - name: shellcheck
      build_script:
        - ./test/shellcheck.sh
