container:
  image: nixos/nix
  # Besides virtualization, this also enables privileged containers which are required for
  # sandboxed builds
  kvm: true
  # Needed for package builds
  memory: 8G

environment:
  CACHIX_SIGNING_KEY: ENCRYPTED[0255dffe6f1c7a05bdb587499dc098123be0fbc9ae73b8c10350352987c0b7225dd6c38d164c042856022dcad354c69d]
  # Save some traffic by excluding the full git history
  CIRRUS_CLONE_DEPTH: 1

task:
  # Use the maximum timeout. Needed when rebuilding packages on a channel update.
  timeout_in: 120m

  matrix:
    - name: modules_test
      environment:
        nixpkgs: nixpkgs
      container:
        # A maximum of 16 CPUs is shared among all concurrent tasks.
        # https://cirrus-ci.org/faq/#are-there-any-limits
        cpu: 4
      matrix:
        - environment:
            scenario: default
        - environment:
            scenario: netns
        - environment:
            scenario: netnsRegtest

    - name: pkgs_unstable
      environment:
        nixpkgs: nixpkgs-unstable

  # This script is run as root
  build_script:
    - echo "sandbox = true" >> /etc/nix/nix.conf
    - export NIX_PATH="nixpkgs=$(nix eval --raw -f pkgs/nixpkgs-pinned.nix $nixpkgs)"
    - nix run -f '<nixpkgs>' bash cachix -c ./ci/build.sh
