task:
  environment:
    CACHIX_SIGNING_KEY: ENCRYPTED[!cec502ed813cbcd0237697d2031f750186ff20eed5815b1ad950ad2f2d701702ae6ba2f0cb4cb1985687a696c8ee492c!]
    # Save some traffic by excluding the full git history
    CIRRUS_CLONE_DEPTH: 1

  # Use the maximum timeout. Needed when rebuilding packages on a channel update.
  timeout_in: 120m

  matrix:
    - name: flake
      container:
        image: nixpkgs/nix-flakes
      build_script:
        - nix flake check
        - ./test/nixos-search/ci-test.sh
