container:
  image: nixos/nix
  # Besides virtualization, this also enables privileged containers which are required for
  # sandboxed builds
  kvm: true
  # Needed for package builds
  memory: 8G

environment:
  CACHIX_SIGNING_KEY: ENCRYPTED[!cec502ed813cbcd0237697d2031f750186ff20eed5815b1ad950ad2f2d701702ae6ba2f0cb4cb1985687a696c8ee492c!]
  # Save some traffic by excluding the full git history
  CIRRUS_CLONE_DEPTH: 1

task:
  # Use the maximum timeout. Needed when rebuilding packages on a channel update.
  timeout_in: 120m

  matrix:
    - container:
        kvm: false
        memory: 2G
        nixpkgs: nixpkgs-unstable
      matrix:
        - name: "flake"
          build_script:
            - echo flake
            - ls -al /dev/kvm
        - name: "flake2"
          container:
            kvm: true
            memory: 4G
            nixpkgs: nixpkgs-unstable
          build_script:
            - echo flake2
            - ls -al /dev/kvm
