dist: bionic # needed for KVM
language: shell

install:
    # Retry installing nix due to nondeterministic error
    #   Fatal error: glibc detected an invalid stdio handle
    # see:
    #   https://github.com/nh2/static-haskell-nix/pull/27#issuecomment-502652181
    #   https://github.com/nixos/nix/issues/2733
  - (for i in {1..5}; do bash <(curl https://nixos.org/nix/install) && exit 0; done; exit 1)
  - . /home/travis/.nix-profile/etc/profile.d/nix.sh
  - if [[ $STABLE == 1 ]]; then export NIX_PATH="nixpkgs=$(nix eval --raw -f pkgs/nixpkgs-pinned.nix nixpkgs)"; fi
  - if [[ $STABLE == 0 ]]; then export NIX_PATH="nixpkgs=$(nix eval --raw -f pkgs/nixpkgs-pinned.nix nixpkgs-unstable)"; fi
  - nix-env -iA cachix -f https://cachix.org/api/v1/install
  - cachix use nix-bitcoin-ci-ea
  - VER="$(nix eval nixpkgs.lib.version)"
env:
  global:
    # CACHIX_SIGNING_KEY
  - secure: "vKzp3WIKGdgtrCRsKP//ac/GP1jMx3r6Kh5qteMbdwVZ0/MuUH5W5/tz47UeNhB7Jv5sZK1MzGb8lcbjOGz9y7Yd7imWsD1hHj8uDt3bWgTHpJB2MP8/Mo8C4/tOxT0dUg5c4C39Zjn9BZtetmksju96cUD+j3OZp79pLmMOA4MHs4bQgxhakggMGuWL16LhupDXJ1YM4xB1ODdSoW0Sc1Cg4eM75k/9VMPB3PvVKtFyUUiXYeSntfLcljSnxQ00xorRsuRP0tMaC9TNZDpkGMbeAHXRhcIHuFwiYmOjhS4FlF3PAGS2W10qOCWteeIoBZW2ce665NhspE5/AJQYaVnMVEtWbA97bvdoqbfa8c6yXYKq66oAQ0Vd2gHq0fW/Nf/gzppyWr7W5t4wozvIHpddL4NrGi+6PebHT1DhUtL3hQu+cu7nFb3WXXI+ZAPRoDMXjQ1MrFIiEglviZofN8uy5KP6bEHHlFrtNNNy5LogoGwQs/f/6J6eRW+Nj/bGgeKEZcPp0b0a0GnT/ms1ThStuJ6rHSN4KSCHjzBlt72xD8P2vkXvJjcb4wAXEEA9No+YUAa6gxamhdqVonnSKDyfJPDBBuG0l3Eea2eiwgjXyWx9qagqAPJ3WqOmguGsRaOxFjsOvgd5f7KQ0mb+hEUqivK4OLgHP6TnWi+eo0I="
  jobs:
  - TestModules=1 STABLE=1
  - PKG=hwi STABLE=1
  - PKG=lightning-charge STABLE=1
  - PKG=lightning-charge STABLE=0
  - PKG=nanopos STABLE=1
  - PKG=nanopos STABLE=0
  - PKG=spark-wallet STABLE=1
  - PKG=elementsd STABLE=1
  - PKG=elementsd STABLE=0
  - PKG=electrs STABLE=1
  # broken
  # - PKG=electrs STABLE=0
  - PKG=liquid-swap STABLE=1
script:
  - printf '%s (%s)\n' "$NIX_PATH" "$VER"
  - |
    getBuildExpr() {
        if [[ $TestModules ]]; then
            if [[ ! -e /dev/kvm ]]; then
                >&2 echo "No KVM available on VM Host."
                exit 1
            fi
            sudo chmod go+rw /dev/kvm
            test/run-tests.sh exprForCI
        else
            echo "(import ./. {}).$PKG"
        fi
    }
  - buildExpr=$(getBuildExpr)
  - time nix-instantiate -E "$buildExpr" --add-root ./drv --indirect
  - outPath=$(nix-store --query ./drv)
  - |
    if nix path-info --store https://nix-bitcoin-ci-ea.cachix.org $outPath &>/dev/null; then
      echo "$outPath" has already been built successfully.
      travis_terminate 0
    fi
    # Travis doesn't expose secrets to pull-request builds,
    # so skip cache uploading in this case
  - |
    if [[ $CACHIX_SIGNING_KEY ]]; then
      cachix push nix-bitcoin-ci-ea --watch-store &
      cachixPid=$!
    fi
  - nix-build ./drv
  - |
    if [[ $CACHIX_SIGNING_KEY ]]; then
      # Wait until cachix has finished uploading
      # Run as root because yama/ptrace_scope != 0
      ruby=$(nix-build '<nixpkgs>' -A ruby)/bin/ruby
      time sudo $ruby helper/wait-for-network-idle.rb $cachixPid
    fi
